version: '3.8'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common

services:
  minio:
    container_name: rdmchat_storage
    image: minio/minio:latest
    env_file: ../../.env
    command: server --console-address ':9001' data1
    ports:
      - '8123:9000'
      - '8124:9001'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - data1-1:/data1
      - data1-2:/data2

volumes:
  data1-1:
  data1-2:
