version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    env_file: ../../.env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
    logging:
      driver: none
