version: '3.8'

services:
  postgres:
    container_name: rdmchat_db
    image: 'postgres:latest'
    env_file: ../../.env
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
      - postgres-dev:/var/lib/postgresql/data
    logging:
      driver: none

volumes:
  postgres-dev:
