name: 'Continuous Integration Testing'

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install g++ gcc libc6 make python -y
          npm install -g node-gyp rimraf

      - name: Install dependencies
        run: yarn install

      - name: Build Argon2
        run: npm_config_build_from_source=true yarn add argon2

      - name: Generate Prisma client
        run: yarn prisma:generate:local

      - name: Run unit tests
        run: yarn test
        env:
          SPACES_BUCKET: cdn-rdmraceapp
